import { CountryCode } from '@prisma/client';

export type SettingKindName = 'STRING' | 'NUMBER' | 'BOOLEAN' | 'JSON' | 'SECRET_REF';
export type SettingInputType = 'text' | 'url' | 'password' | 'number' | 'boolean' | 'json' | 'countries';

export type SettingDefinition = {
  key: string;
  label: string;
  group: string;
  kind: SettingKindName;
  input: SettingInputType;
  envKey?: string;
  defaultValue: unknown;
  description?: string;
  isSecret?: boolean;
  masked?: boolean;
  options?: Array<{ label: string; value: string }>;
};

export const GCC_COUNTRY_CODES = [CountryCode.SA, CountryCode.AE, CountryCode.KW, CountryCode.QA, CountryCode.BH, CountryCode.OM] as const;

export const COUNTRY_OPTIONS = [
  { value: CountryCode.SA, label: 'Saudi Arabia / KSA' },
  { value: CountryCode.AE, label: 'United Arab Emirates' },
  { value: CountryCode.KW, label: 'Kuwait' },
  { value: CountryCode.QA, label: 'Qatar' },
  { value: CountryCode.BH, label: 'Bahrain' },
  { value: CountryCode.OM, label: 'Oman' },
];

export const SETTINGS: SettingDefinition[] = [
  {
    key: 'country.default',
    label: 'Default import country',
    group: 'Country and sync',
    kind: 'STRING',
    input: 'text',
    envKey: 'IMPORT_DEFAULT_COUNTRY',
    defaultValue: CountryCode.SA,
    description: 'Used when an API/job request does not provide a country.',
    options: COUNTRY_OPTIONS,
  },
  {
    key: 'country.enabled',
    label: 'Enabled import countries',
    group: 'Country and sync',
    kind: 'JSON',
    input: 'countries',
    defaultValue: [CountryCode.SA, CountryCode.AE, CountryCode.KW, CountryCode.QA, CountryCode.BH, CountryCode.OM],
    description: 'Dashboard discovery and stock sync can run for any selected COD Network GCC country.',
  },
  {
    key: 'sync.frequencyCron',
    label: 'Sync frequency cron',
    group: 'Country and sync',
    kind: 'STRING',
    input: 'text',
    defaultValue: '17 */2 * * *',
  },
  {
    key: 'visibility.default',
    label: 'Default product visibility',
    group: 'Country and sync',
    kind: 'BOOLEAN',
    input: 'boolean',
    defaultValue: true,
  },
  {
    key: 'pricing.defaultFormula',
    label: 'Default pricing formula JSON',
    group: 'Pricing and discounts',
    kind: 'JSON',
    input: 'json',
    defaultValue: { type: 'markup_percent', value: 60, roundTo: 0.99 },
    description: 'Used when COD does not provide a recommended selling price.',
  },
  {
    key: 'codNetwork.baseUrl',
    label: 'COD Network base URL',
    group: 'COD Network',
    kind: 'STRING',
    input: 'url',
    envKey: 'COD_NETWORK_BASE_URL',
    defaultValue: 'https://api.cod.network/v2',
    masked: true,
  },
  {
    key: 'codNetwork.apiToken',
    label: 'COD Network API token',
    group: 'COD Network',
    kind: 'SECRET_REF',
    input: 'password',
    envKey: 'COD_NETWORK_API_TOKEN',
    defaultValue: '',
    isSecret: true,
    masked: true,
  },
  {
    key: 'codNetwork.catalogEndpoint',
    label: 'Catalog/marketplace products endpoint',
    group: 'COD Network',
    kind: 'STRING',
    input: 'text',
    envKey: 'COD_NETWORK_CATALOG_ENDPOINT',
    defaultValue: '/seller/marketplace/products',
    masked: true,
  },
  {
    key: 'codNetwork.accountProductsEndpoint',
    label: 'Seller account/drop products endpoint',
    group: 'COD Network',
    kind: 'STRING',
    input: 'text',
    envKey: 'COD_NETWORK_ACCOUNT_PRODUCTS_ENDPOINT',
    defaultValue: '/seller/drop-products',
    masked: true,
  },
  {
    key: 'codNetwork.addProductEndpoint',
    label: 'Add/select product endpoint',
    group: 'COD Network',
    kind: 'STRING',
    input: 'text',
    envKey: 'COD_NETWORK_ADD_PRODUCT_ENDPOINT',
    defaultValue: '',
    masked: true,
    description: 'Official COD endpoint used to add/select a marketplace product into the seller account.',
  },
  {
    key: 'codNetwork.webhookSecret',
    label: 'COD webhook secret',
    group: 'COD Network',
    kind: 'SECRET_REF',
    input: 'password',
    envKey: 'COD_NETWORK_WEBHOOK_SECRET',
    defaultValue: '',
    isSecret: true,
    masked: true,
  },
  {
    key: 'codNetwork.productPageUrlTemplate',
    label: 'COD product page URL template',
    group: 'COD Network',
    kind: 'STRING',
    input: 'url',
    envKey: 'COD_NETWORK_PRODUCT_PAGE_URL_TEMPLATE',
    defaultValue: '',
    masked: true,
    description: 'Optional. Supports {codProductId}, {codDropProductId}, {codSku}, and {country}. Used when COD raw payload does not include a product URL.',
  },
  {
    key: 'youCan.baseUrl',
    label: 'YouCan API base URL',
    group: 'YouCan',
    kind: 'STRING',
    input: 'url',
    envKey: 'YOUCAN_BASE_URL',
    defaultValue: 'https://api.youcan.shop',
    masked: true,
  },
  {
    key: 'youCan.apiToken',
    label: 'YouCan API token',
    group: 'YouCan',
    kind: 'SECRET_REF',
    input: 'password',
    envKey: 'YOUCAN_API_TOKEN',
    defaultValue: '',
    isSecret: true,
    masked: true,
  },
  {
    key: 'youCan.clientId',
    label: 'YouCan OAuth client ID',
    group: 'YouCan',
    kind: 'SECRET_REF',
    input: 'password',
    envKey: 'YOUCAN_CLIENT_ID',
    defaultValue: '',
    isSecret: true,
    masked: true,
  },
  {
    key: 'youCan.clientSecret',
    label: 'YouCan OAuth client secret',
    group: 'YouCan',
    kind: 'SECRET_REF',
    input: 'password',
    envKey: 'YOUCAN_CLIENT_SECRET',
    defaultValue: '',
    isSecret: true,
    masked: true,
  },
  {
    key: 'youCan.redirectUri',
    label: 'YouCan OAuth redirect URI',
    group: 'YouCan',
    kind: 'STRING',
    input: 'url',
    envKey: 'YOUCAN_REDIRECT_URI',
    defaultValue: 'https://app.example.com/api/youcan/oauth/callback',
    masked: true,
  },
  {
    key: 'youCan.refreshToken',
    label: 'YouCan OAuth refresh token',
    group: 'YouCan',
    kind: 'SECRET_REF',
    input: 'password',
    envKey: 'YOUCAN_REFRESH_TOKEN',
    defaultValue: '',
    isSecret: true,
    masked: true,
  },
  {
    key: 'youCan.storeUrl',
    label: 'YouCan store URL',
    group: 'YouCan',
    kind: 'STRING',
    input: 'url',
    envKey: 'YOUCAN_STORE_URL',
    defaultValue: '',
    masked: true,
  },
  {
    key: 'youCan.textButtonVariantType',
    label: 'YouCan text-button variant type',
    group: 'YouCan',
    kind: 'NUMBER',
    input: 'number',
    envKey: 'YOUCAN_TEXT_BUTTON_VARIANT_TYPE',
    defaultValue: 2,
  },
  {
    key: 'youCan.quantityOptionName',
    label: 'Quantity option name',
    group: 'YouCan',
    kind: 'STRING',
    input: 'text',
    envKey: 'YOUCAN_QUANTITY_OPTION_NAME',
    defaultValue: 'الكمية',
    description: 'YouCan variant option name shown above quantity buttons.',
  },
  {
    key: 'youCan.singleQuantityLabel',
    label: 'Single quantity variant label',
    group: 'YouCan',
    kind: 'STRING',
    input: 'text',
    envKey: 'YOUCAN_SINGLE_QUANTITY_LABEL',
    defaultValue: 'قطعة واحدة',
    description: 'Variant value used for one item. Multi-item labels come from discount variant rule labels below.',
  },
  {
    key: 'googleMerchant.accountId',
    label: 'Google Merchant account ID',
    group: 'Google Merchant Center',
    kind: 'SECRET_REF',
    input: 'password',
    envKey: 'GOOGLE_MERCHANT_ACCOUNT_ID',
    defaultValue: '',
    isSecret: true,
    masked: true,
  },
  {
    key: 'googleMerchant.dataSourceId',
    label: 'Google Merchant data source ID',
    group: 'Google Merchant Center',
    kind: 'SECRET_REF',
    input: 'password',
    envKey: 'GOOGLE_MERCHANT_DATA_SOURCE_ID',
    defaultValue: '',
    isSecret: true,
    masked: true,
  },
  {
    key: 'googleMerchant.enabled',
    label: 'Enable Google Merchant push',
    group: 'Google Merchant Center',
    kind: 'BOOLEAN',
    input: 'boolean',
    envKey: 'GOOGLE_MERCHANT_ENABLED',
    defaultValue: false,
  },
  {
    key: 'gmc.feedLabel',
    label: 'GMC feed label',
    group: 'Google Merchant Center',
    kind: 'STRING',
    input: 'text',
    envKey: 'GMC_FEED_LABEL',
    defaultValue: 'SA',
  },
  {
    key: 'gmc.contentLanguage',
    label: 'GMC content language',
    group: 'Google Merchant Center',
    kind: 'STRING',
    input: 'text',
    envKey: 'GMC_CONTENT_LANGUAGE',
    defaultValue: 'ar',
  },
  {
    key: 'googleMerchant.applicationCredentials',
    label: 'Google credentials file path',
    group: 'Google Merchant Center',
    kind: 'SECRET_REF',
    input: 'password',
    envKey: 'GOOGLE_APPLICATION_CREDENTIALS',
    defaultValue: '',
    isSecret: true,
    masked: true,
  },
  {
    key: 'googleMerchant.serviceAccountJson',
    label: 'Google service account JSON',
    group: 'Google Merchant Center',
    kind: 'SECRET_REF',
    input: 'password',
    envKey: 'GOOGLE_SERVICE_ACCOUNT_JSON',
    defaultValue: '',
    isSecret: true,
    masked: true,
  },
  {
    key: 'ai.provider',
    label: 'AI provider name',
    group: 'AI provider',
    kind: 'STRING',
    input: 'text',
    envKey: 'AI_PROVIDER_NAME',
    defaultValue: 'DuckCoding',
  },
  {
    key: 'ai.baseUrl',
    label: 'OpenAI-compatible base URL',
    group: 'AI provider',
    kind: 'STRING',
    input: 'url',
    envKey: 'AI_BASE_URL',
    defaultValue: 'https://www.duckcoding.ai/',
    masked: true,
  },
  {
    key: 'ai.apiKey',
    label: 'AI API key',
    group: 'AI provider',
    kind: 'SECRET_REF',
    input: 'password',
    envKey: 'AI_API_KEY',
    defaultValue: '',
    isSecret: true,
    masked: true,
  },
  {
    key: 'ai.model',
    label: 'AI model',
    group: 'AI provider',
    kind: 'STRING',
    input: 'text',
    envKey: 'AI_MODEL',
    defaultValue: 'claude-opus-4-8',
  },
  {
    key: 'webSearch.provider',
    label: 'Web search provider',
    group: 'Image enrichment and web search',
    kind: 'STRING',
    input: 'text',
    envKey: 'WEB_SEARCH_PROVIDER',
    defaultValue: 'manual',
  },
  {
    key: 'webSearch.apiKey',
    label: 'Web search API key',
    group: 'Image enrichment and web search',
    kind: 'SECRET_REF',
    input: 'password',
    envKey: 'WEB_SEARCH_API_KEY',
    defaultValue: '',
    isSecret: true,
    masked: true,
  },
  {
    key: 'image.serperApiKey',
    label: 'Serper API key',
    group: 'Image enrichment and web search',
    kind: 'SECRET_REF',
    input: 'password',
    envKey: 'SERPER_API_KEY',
    defaultValue: '',
    isSecret: true,
    masked: true,
    description: 'Primary Google Images provider from serper.dev used before SerpApi/Bright Data fallbacks.',
  },
  {
    key: 'image.serpApiKey',
    label: 'SerpApi API key',
    group: 'Image enrichment and web search',
    kind: 'SECRET_REF',
    input: 'password',
    envKey: 'SERPAPI_API_KEY',
    defaultValue: '',
    isSecret: true,
    masked: true,
  },
  {
    key: 'image.brightDataApiKey',
    label: 'Bright Data API key',
    group: 'Image enrichment and web search',
    kind: 'SECRET_REF',
    input: 'password',
    envKey: 'BRIGHTDATA_API_KEY',
    defaultValue: '',
    isSecret: true,
    masked: true,
  },
  {
    key: 'image.brightDataSerpZone',
    label: 'Bright Data SERP zone',
    group: 'Image enrichment and web search',
    kind: 'STRING',
    input: 'text',
    envKey: 'BRIGHTDATA_SERP_ZONE',
    defaultValue: 'serp_api1',
  },
  {
    key: 'image.enrichmentTargetCount',
    label: 'Image enrichment target count',
    group: 'Image enrichment and web search',
    kind: 'NUMBER',
    input: 'number',
    envKey: 'IMAGE_ENRICHMENT_TARGET_COUNT',
    defaultValue: 5,
  },
  {
    key: 'image.enrichmentMaxCandidates',
    label: 'Max image candidates to validate',
    group: 'Image enrichment and web search',
    kind: 'NUMBER',
    input: 'number',
    envKey: 'IMAGE_ENRICHMENT_MAX_CANDIDATES',
    defaultValue: 35,
  },
  {
    key: 'image.validationTimeoutMs',
    label: 'Image validation timeout (ms)',
    group: 'Image enrichment and web search',
    kind: 'NUMBER',
    input: 'number',
    envKey: 'IMAGE_VALIDATION_TIMEOUT_MS',
    defaultValue: 5000,
  },
  {
    key: 'app.baseUrl',
    label: 'App base URL',
    group: 'App and deployment',
    kind: 'STRING',
    input: 'url',
    envKey: 'APP_BASE_URL',
    defaultValue: 'https://app.example.com',
    masked: true,
  },
  {
    key: 'app.adminPassword',
    label: 'Admin password override',
    group: 'App and deployment',
    kind: 'SECRET_REF',
    input: 'password',
    envKey: 'ADMIN_PASSWORD',
    defaultValue: '',
    isSecret: true,
    masked: true,
    description: 'Login/middleware still require the server env password for full protection; keep the VPS .env.production value in sync.',
  },
  {
    key: 'worker.concurrency',
    label: 'Worker concurrency',
    group: 'App and deployment',
    kind: 'NUMBER',
    input: 'number',
    envKey: 'WORKER_CONCURRENCY',
    defaultValue: 4,
    description: 'Changing this requires a worker restart to affect an already-running worker.',
  },
];

export const SETTINGS_BY_KEY = new Map(SETTINGS.map((definition) => [definition.key, definition]));

export function groupedSettings() {
  const groups = new Map<string, SettingDefinition[]>();
  for (const definition of SETTINGS) {
    const list = groups.get(definition.group) ?? [];
    list.push(definition);
    groups.set(definition.group, list);
  }
  return [...groups.entries()].map(([group, definitions]) => ({ group, definitions }));
}
